services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/base-gin-go
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
#    command: go run main.go -b 0.0.0.0
    command: air
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/db_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: base-gin-go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

#Docker Networks
volumes:
  db_data:
    driver: local